;;; test-export.el --- the description written for tools outside Emacs -*- lexical-binding: t; -*-
;; Run with: emacs --batch -l test/test-export.el

(add-to-list 'load-path (expand-file-name "../lisp" (file-name-directory load-file-name)))
(require 'org)
(require 'paragtd)

(defvar paragtd-test-failures 0)
(defun paragtd-test-check (ok what)
  (princ (format "%s %s\n" (if ok "PASS" "FAIL") what))
  (unless ok (setq paragtd-test-failures (1+ paragtd-test-failures))))

(let* ((dir (make-temp-file "paragtd-export" t))
       (paragtd-org-directory dir)
       (paragtd-roam-directory (expand-file-name "roam" dir))
       (paragtd-capture-extra-templates
        '(("x" "Site template" entry (file+headline "extra.org" "Stuff") "* TODO %?\n")
          ("f" "A function" entry (file "f.org") (function ignore))
          ("r" "A prefix")
          ("d" "A week tree" entry (file+olp+datetree "j.org") "* %U %?\n" :tree-type week)))
       (org-capture-templates nil))
  (paragtd-setup)
  (paragtd-test-check (not (file-exists-p (expand-file-name ".paragtd.json" dir))) "setup writes nothing in batch")
  (let* ((file (paragtd-export))
         (json-object-type 'alist) (json-array-type 'list) (json-key-type 'symbol)
         (got (json-read-file file))
         (keys (mapcar (lambda (c) (alist-get 'key c)) (alist-get 'capture got))))
    (paragtd-test-check (equal (file-name-nondirectory file) ".paragtd.json") "written into the Org directory")
    (paragtd-test-check (equal (alist-get 'roam_directory got) "roam") "roam relative to it")
    (paragtd-test-check (member "next-actions.org" (alist-get 'files got)) "the core files")
    (paragtd-test-check (equal (car (alist-get 'todo_keywords got))
                               '("TODO(t)" "NEXT(n)" "WAITING(w@/!)" "|" "DONE(d!)" "CANCELLED(c@)"))
                        "the keywords, keys kept")
    (paragtd-test-check (and (member "p" keys) (member "x" keys)) "core and site templates")
    (paragtd-test-check (not (or (member "f" keys) (member "r" keys))) "no function templates, no prefixes")
    (paragtd-test-check (equal (alist-get 'headline (seq-find (lambda (c) (equal (alist-get 'key c) "x"))
                                                              (alist-get 'capture got)))
                               "Stuff")
                        "a headline target keeps its headline")
    (paragtd-test-check (equal (alist-get 'tree_type (seq-find (lambda (c) (equal (alist-get 'key c) "d"))
                                                               (alist-get 'capture got)))
                               "week")
                        "a date tree says which kind")
    (paragtd-test-check (equal (alist-get 'next_keyword (alist-get 'sequence got)) "NEXT") "sequencing")
    (let ((mtime (file-attribute-modification-time (file-attributes file))))
      (sleep-for 1.1)
      (paragtd-export)
      (paragtd-test-check (equal mtime (file-attribute-modification-time (file-attributes file)))
                          "unchanged content is not rewritten"))))

(kill-emacs (if (zerop paragtd-test-failures) 0 1))
